# Generated by Django 4.1.5 on 2023-01-10 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='trackedTime',
            new_name='tracked_time',
        ),
    ]
