# Generated by Django 4.1.4 on 2022-12-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='trackedTime',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
