# Generated by Django 4.1.5 on 2023-01-10 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_rename_trackedtime_action_tracked_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='actionDate',
            new_name='action_date',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='activeTrackedTime',
            new_name='active_tracked_time',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='doneStatus',
            new_name='done_status',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='trackedStart',
            new_name='tracked_start',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='trackedStop',
            new_name='tracked_stop',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='trackingStatus',
            new_name='tracking_status',
        ),
    ]
