# Generated by Django 4.1.4 on 2023-01-01 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0005_category_user_priority_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='date',
            new_name='actionDate',
        ),
    ]
