# Generated by Django 4.1.5 on 2023-01-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0007_action_trackedstart_action_trackedstop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='trackedTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
