# Generated by Django 4.1.5 on 2023-01-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0008_alter_action_trackedtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='activeTimeTracked',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
