# Generated by Django 4.1.5 on 2023-01-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0010_alter_action_activetimetracked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='activeTimeTracked',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='trackedTime',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
