# Generated by Django 4.1.5 on 2023-01-02 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0012_alter_action_activetimetracked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='activeTimeTracked',
        ),
    ]
