# Generated by Django 4.1.5 on 2023-01-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0013_remove_action_activetimetracked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='trackedStart',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='trackedStop',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='trackedTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
