# Generated by Django 4.1.4 on 2023-01-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0014_alter_action_trackedstart_alter_action_trackedstop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='trackingStatus',
            field=models.BooleanField(default=False),
        ),
    ]
