# Generated by Django 4.1.4 on 2023-01-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0017_alter_action_trackedtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='trackedTime',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
