# Generated by Django 4.1.4 on 2023-01-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0018_alter_action_trackedtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='activeTrackedTime',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
