# Generated by Django 4.1.4 on 2023-01-04 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0024_alter_action_activetrackedtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='priority',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actions.category'),
        ),
        migrations.AlterField(
            model_name='action',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actions.category'),
        ),
        migrations.AlterField(
            model_name='action',
            name='priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actions.priority'),
        ),
    ]
