# Generated by Django 4.1.4 on 2023-01-04 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('actions', '0025_priority_category_alter_action_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportDate', models.DateTimeField(auto_now_add=True)),
                ('timeTrackedToday', models.DurationField(blank=True, null=True)),
                ('actionsCompleted', models.IntegerField(blank=True, null=True)),
                ('openActions', models.IntegerField(blank=True, null=True)),
                ('percOnPriority', models.FloatField(blank=True, null=True)),
                ('percOffPriority', models.FloatField(blank=True, null=True)),
                ('timeOnPriority', models.DurationField(blank=True, null=True)),
                ('timeOffPriority', models.DurationField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
