# Generated by Django 4.1.4 on 2023-01-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0027_trackingreport_delete_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingreport',
            name='reportDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
