# Generated by Django 4.1.4 on 2023-01-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0028_alter_trackingreport_reportdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingreport',
            name='reportDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
