# Generated by Django 4.1.4 on 2023-01-04 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0030_alter_trackingreport_reportdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrackingReport',
        ),
    ]
